--
-- PostgreSQL database dump
--

\restrict ga75RPSI9oibSZSNDPFHBDAi9ZbRlATAevVqqYpilIxFJvMiaV1BNHObJZlLaAc

-- Dumped from database version 18.6
-- Dumped by pg_dump version 18.6

-- Started on 2026-10-06 17:37:41

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 223 (class 1259 OID 32827)
-- Name: categories; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.categories (
    id bigint NOT NULL,
    code bigint NOT NULL,
    name character varying(255) NOT NULL,
    is_active boolean DEFAULT true CONSTRAINT "categories_is-active_not_null" NOT NULL
);


ALTER TABLE public.categories OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 32863)
-- Name: request_assignments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.request_assignments (
    id bigint NOT NULL,
    request_id bigint NOT NULL,
    assigned_to bigint NOT NULL,
    offered_by bigint NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    responded_at timestamp without time zone,
    state character varying(255) NOT NULL,
    CONSTRAINT responded_after_created CHECK (((responded_at IS NULL) OR (responded_at >= created_at))),
    CONSTRAINT self_assign_same_user CHECK ((((state)::text <> 'self_assigned'::text) OR (assigned_to = offered_by))),
    CONSTRAINT state_options CHECK (((state)::text = ANY ((ARRAY['offered'::character varying, 'accepted'::character varying, 'declined'::character varying, 'self_assigned'::character varying])::text[])))
);


ALTER TABLE public.request_assignments OWNER TO postgres;

--
-- TOC entry 228 (class 1259 OID 32875)
-- Name: request_assignments_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.request_assignments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.request_assignments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 229 (class 1259 OID 32876)
-- Name: request_comments; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.request_comments (
    id bigint NOT NULL,
    request_id bigint NOT NULL,
    author_id bigint NOT NULL,
    comment text NOT NULL,
    is_resolution boolean DEFAULT false NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);


ALTER TABLE public.request_comments OWNER TO postgres;

--
-- TOC entry 230 (class 1259 OID 32890)
-- Name: request_comments_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.request_comments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.request_comments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 224 (class 1259 OID 32837)
-- Name: request_status_history; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.request_status_history (
    id bigint NOT NULL,
    request_id bigint NOT NULL,
    old_status character varying(255),
    new_status character varying(255) NOT NULL,
    changed_by bigint NOT NULL,
    changed_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT new_status_options_check CHECK (((new_status)::text = ANY ((ARRAY['open'::character varying, 'assigned'::character varying, 'in_progress'::character varying, 'resolved'::character varying, 'closed'::character varying])::text[]))),
    CONSTRAINT old_status_first_entry_check CHECK (((old_status IS NOT NULL) OR ((new_status)::text = 'open'::text))),
    CONSTRAINT old_status_options_check CHECK (((old_status)::text = ANY ((ARRAY['open'::character varying, 'assigned'::character varying, 'in_progress'::character varying, 'resolved'::character varying, 'closed'::character varying])::text[])))
);


ALTER TABLE public.request_status_history OWNER TO postgres;

--
-- TOC entry 225 (class 1259 OID 32853)
-- Name: request_status_history_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.request_status_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.request_status_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 32854)
-- Name: request_status_transition; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.request_status_transition (
    old_status character varying(255) NOT NULL,
    new_status character varying(255) NOT NULL
);


ALTER TABLE public.request_status_transition OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 32777)
-- Name: service_request; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.service_request (
    id bigint CONSTRAINT "service_request_request_ID_not_null" NOT NULL,
    reference_number bigint NOT NULL,
    requestor_id bigint CONSTRAINT "service_request_requestor_ID_not_null" NOT NULL,
    location character varying(255) NOT NULL,
    area character varying(255) NOT NULL,
    description text NOT NULL,
    status character varying(255) DEFAULT 'open'::character varying NOT NULL,
    assigned_to bigint,
    version bigint DEFAULT 0 NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    resolved_at timestamp without time zone,
    category_id bigint NOT NULL,
    CONSTRAINT resolved_after_updated_sanity_check CHECK (((resolved_at IS NULL) OR (resolved_at >= created_at))),
    CONSTRAINT resolved_has_time CHECK ((((status)::text <> ALL ((ARRAY['resolved'::character varying, 'closed'::character varying])::text[])) OR (resolved_at IS NOT NULL))),
    CONSTRAINT status_check CHECK (((status)::text = ANY ((ARRAY['open'::character varying, 'assigned'::character varying, 'in_progress'::character varying, 'resolved'::character varying, 'closed'::character varying])::text[]))),
    CONSTRAINT updated_after_created_sanity_check CHECK ((updated_at >= created_at)),
    CONSTRAINT version_not_negative CHECK ((version >= 0))
);


ALTER TABLE public.service_request OWNER TO postgres;

--
-- TOC entry 220 (class 1259 OID 32801)
-- Name: service_request_request_ID_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.service_request ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."service_request_request_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 32802)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id bigint CONSTRAINT "Users_id_not_null" NOT NULL,
    name character varying(255) CONSTRAINT "Users_name_not_null" NOT NULL,
    email character varying(255) CONSTRAINT "Users_email_not_null" NOT NULL,
    password character varying(255) CONSTRAINT "Users_password_not_null" NOT NULL,
    role character varying(255) DEFAULT 'requestor'::character varying CONSTRAINT "Users_role_not_null" NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP CONSTRAINT "Users_created_at_not_null" NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP CONSTRAINT "Users_updated_at_not_null" NOT NULL,
    CONSTRAINT role_options CHECK (((role)::text = ANY ((ARRAY['requestor'::character varying, 'staff'::character varying, 'management'::character varying])::text[]))),
    CONSTRAINT update_after_created_sanity_check CHECK ((updated_at >= created_at))
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 222 (class 1259 OID 32822)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 5102 (class 0 OID 32827)
-- Dependencies: 223
-- Data for Name: categories; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.categories (id, code, name, is_active) FROM stdin;
\.


--
-- TOC entry 5106 (class 0 OID 32863)
-- Dependencies: 227
-- Data for Name: request_assignments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.request_assignments (id, request_id, assigned_to, offered_by, created_at, responded_at, state) FROM stdin;
\.


--
-- TOC entry 5108 (class 0 OID 32876)
-- Dependencies: 229
-- Data for Name: request_comments; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.request_comments (id, request_id, author_id, comment, is_resolution, created_at) FROM stdin;
\.


--
-- TOC entry 5103 (class 0 OID 32837)
-- Dependencies: 224
-- Data for Name: request_status_history; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.request_status_history (id, request_id, old_status, new_status, changed_by, changed_at) FROM stdin;
\.


--
-- TOC entry 5105 (class 0 OID 32854)
-- Dependencies: 226
-- Data for Name: request_status_transition; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.request_status_transition (old_status, new_status) FROM stdin;
open	assigned
assigned	in_progress
in_progress	resolved
resolved	closed
resolved	in_progress
\.


--
-- TOC entry 5098 (class 0 OID 32777)
-- Dependencies: 219
-- Data for Name: service_request; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.service_request (id, reference_number, requestor_id, location, area, description, status, assigned_to, version, created_at, updated_at, resolved_at, category_id) FROM stdin;
\.


--
-- TOC entry 5100 (class 0 OID 32802)
-- Dependencies: 221
-- Data for Name: users; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.users (id, name, email, password, role, created_at, updated_at) FROM stdin;
\.


--
-- TOC entry 5115 (class 0 OID 0)
-- Dependencies: 228
-- Name: request_assignments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.request_assignments_id_seq', 1, false);


--
-- TOC entry 5116 (class 0 OID 0)
-- Dependencies: 230
-- Name: request_comments_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.request_comments_id_seq', 1, false);


--
-- TOC entry 5117 (class 0 OID 0)
-- Dependencies: 225
-- Name: request_status_history_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.request_status_history_id_seq', 1, false);


--
-- TOC entry 5118 (class 0 OID 0)
-- Dependencies: 220
-- Name: service_request_request_ID_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public."service_request_request_ID_seq"', 1, false);


--
-- TOC entry 5119 (class 0 OID 0)
-- Dependencies: 222
-- Name: users_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.users_id_seq', 1, false);


--
-- TOC entry 4917 (class 2606 OID 32819)
-- Name: users Users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT "Users_pkey" PRIMARY KEY (id);


--
-- TOC entry 4921 (class 2606 OID 32836)
-- Name: categories categories_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);


--
-- TOC entry 4935 (class 2606 OID 32874)
-- Name: request_assignments request_assignments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.request_assignments
    ADD CONSTRAINT request_assignments_pkey PRIMARY KEY (id);


--
-- TOC entry 4939 (class 2606 OID 32889)
-- Name: request_comments request_comments_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.request_comments
    ADD CONSTRAINT request_comments_pkey PRIMARY KEY (id);


--
-- TOC entry 4928 (class 2606 OID 32850)
-- Name: request_status_history request_status_history_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.request_status_history
    ADD CONSTRAINT request_status_history_pkey PRIMARY KEY (id);


--
-- TOC entry 4930 (class 2606 OID 32862)
-- Name: request_status_transition request_status_transition_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.request_status_transition
    ADD CONSTRAINT request_status_transition_pkey PRIMARY KEY (old_status, new_status);


--
-- TOC entry 4913 (class 2606 OID 32800)
-- Name: service_request service_request_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.service_request
    ADD CONSTRAINT service_request_pkey PRIMARY KEY (id);


--
-- TOC entry 4923 (class 2606 OID 32892)
-- Name: categories unique_code; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT unique_code UNIQUE (code);


--
-- TOC entry 4919 (class 2606 OID 32821)
-- Name: users unique_email; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT unique_email UNIQUE (email);


--
-- TOC entry 4915 (class 2606 OID 32826)
-- Name: service_request unique_reference; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.service_request
    ADD CONSTRAINT unique_reference UNIQUE (reference_number);


--
-- TOC entry 4931 (class 1259 OID 32930)
-- Name: fki_assigned_to_link; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX fki_assigned_to_link ON public.request_assignments USING btree (assigned_to);


--
-- TOC entry 4936 (class 1259 OID 32947)
-- Name: fki_author_link; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX fki_author_link ON public.request_comments USING btree (author_id);


--
-- TOC entry 4909 (class 1259 OID 32981)
-- Name: fki_category_id_link; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX fki_category_id_link ON public.service_request USING btree (category_id);


--
-- TOC entry 4924 (class 1259 OID 32969)
-- Name: fki_changed_by_link; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX fki_changed_by_link ON public.request_status_history USING btree (changed_by);


--
-- TOC entry 4932 (class 1259 OID 32936)
-- Name: fki_offered_by_link; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX fki_offered_by_link ON public.request_assignments USING btree (offered_by);


--
-- TOC entry 4933 (class 1259 OID 32924)
-- Name: fki_request_id_link; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX fki_request_id_link ON public.request_assignments USING btree (request_id);


--
-- TOC entry 4910 (class 1259 OID 32975)
-- Name: fki_requestor_id_link; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX fki_requestor_id_link ON public.service_request USING btree (requestor_id);


--
-- TOC entry 4925 (class 1259 OID 32963)
-- Name: fki_status_links; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX fki_status_links ON public.request_status_history USING btree (old_status, new_status);


--
-- TOC entry 4937 (class 1259 OID 33081)
-- Name: idx_comments_request_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_comments_request_id ON public.request_comments USING btree (request_id);


--
-- TOC entry 4926 (class 1259 OID 33082)
-- Name: idx_history_request_id; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_history_request_id ON public.request_status_history USING btree (request_id);


--
-- TOC entry 4911 (class 1259 OID 33083)
-- Name: idx_requests_assigned_to; Type: INDEX; Schema: public; Owner: postgres
--

CREATE INDEX idx_requests_assigned_to ON public.service_request USING btree (assigned_to);


--
-- TOC entry 4946 (class 2606 OID 32925)
-- Name: request_assignments assigned_to_link; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.request_assignments
    ADD CONSTRAINT assigned_to_link FOREIGN KEY (assigned_to) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- TOC entry 4940 (class 2606 OID 32982)
-- Name: service_request assigned_to_link; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.service_request
    ADD CONSTRAINT assigned_to_link FOREIGN KEY (assigned_to) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- TOC entry 4949 (class 2606 OID 32942)
-- Name: request_comments author_link; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.request_comments
    ADD CONSTRAINT author_link FOREIGN KEY (author_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- TOC entry 4941 (class 2606 OID 32976)
-- Name: service_request category_id_link; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.service_request
    ADD CONSTRAINT category_id_link FOREIGN KEY (category_id) REFERENCES public.categories(id) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- TOC entry 4943 (class 2606 OID 32964)
-- Name: request_status_history changed_by_link; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.request_status_history
    ADD CONSTRAINT changed_by_link FOREIGN KEY (changed_by) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- TOC entry 4947 (class 2606 OID 32931)
-- Name: request_assignments offered_by_link; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.request_assignments
    ADD CONSTRAINT offered_by_link FOREIGN KEY (offered_by) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- TOC entry 4948 (class 2606 OID 32919)
-- Name: request_assignments request_id_link; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.request_assignments
    ADD CONSTRAINT request_id_link FOREIGN KEY (request_id) REFERENCES public.service_request(id) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- TOC entry 4950 (class 2606 OID 32937)
-- Name: request_comments request_id_link; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.request_comments
    ADD CONSTRAINT request_id_link FOREIGN KEY (request_id) REFERENCES public.service_request(id) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- TOC entry 4944 (class 2606 OID 32953)
-- Name: request_status_history request_id_link; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.request_status_history
    ADD CONSTRAINT request_id_link FOREIGN KEY (request_id) REFERENCES public.service_request(id) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- TOC entry 4942 (class 2606 OID 32970)
-- Name: service_request requestor_id_link; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.service_request
    ADD CONSTRAINT requestor_id_link FOREIGN KEY (requestor_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE RESTRICT;


--
-- TOC entry 4945 (class 2606 OID 33084)
-- Name: request_status_history status_links; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.request_status_history
    ADD CONSTRAINT status_links FOREIGN KEY (old_status, new_status) REFERENCES public.request_status_transition(old_status, new_status) ON UPDATE RESTRICT ON DELETE RESTRICT;


-- Completed on 2026-10-06 17:37:41

--
-- PostgreSQL database dump complete
--

\unrestrict ga75RPSI9oibSZSNDPFHBDAi9ZbRlATAevVqqYpilIxFJvMiaV1BNHObJZlLaAc

