
CREATE TABLE public.categories (
    id bigint NOT NULL,
    code bigint NOT NULL,
    name character varying(255) NOT NULL,
    is_active boolean DEFAULT true CONSTRAINT "categories_is-active_not_null" NOT NULL
);

CREATE TABLE public.request_assignments (
    id bigint NOT NULL,
    request_id bigint NOT NULL,
    assigned_to bigint NOT NULL,
    offered_by bigint NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    responded_at timestamp without time zone,
    state character varying(255) NOT NULL,
    CONSTRAINT responded_after_created CHECK (((responded_at IS NULL) OR (responded_at >= created_at))),
    CONSTRAINT self_assign_same_user CHECK ((((state)::text <> 'self_assigned'::text) OR (assigned_to = offered_by))),
    CONSTRAINT state_options CHECK (((state)::text = ANY ((ARRAY['offered'::character varying, 'accepted'::character varying, 'declined'::character varying, 'self_assigned'::character varying])::text[])))
);

ALTER TABLE public.request_assignments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.request_assignments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.request_comments (
    id bigint NOT NULL,
    request_id bigint NOT NULL,
    author_id bigint NOT NULL,
    comment text NOT NULL,
    is_resolution boolean DEFAULT false NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL
);

ALTER TABLE public.request_comments ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.request_comments_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.request_status_history (
    id bigint NOT NULL,
    request_id bigint NOT NULL,
    old_status character varying(255),
    new_status character varying(255) NOT NULL,
    changed_by bigint NOT NULL,
    changed_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT new_status_options_check CHECK (((new_status)::text = ANY ((ARRAY['open'::character varying, 'assigned'::character varying, 'in_progress'::character varying, 'resolved'::character varying, 'closed'::character varying])::text[]))),
    CONSTRAINT old_status_first_entry_check CHECK (((old_status IS NOT NULL) OR ((new_status)::text = 'open'::text))),
    CONSTRAINT old_status_options_check CHECK (((old_status)::text = ANY ((ARRAY['open'::character varying, 'assigned'::character varying, 'in_progress'::character varying, 'resolved'::character varying, 'closed'::character varying])::text[])))
);

ALTER TABLE public.request_status_history ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.request_status_history_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.request_status_transition (
    old_status character varying(255) NOT NULL,
    new_status character varying(255) NOT NULL
);

CREATE TABLE public.service_request (
    id bigint CONSTRAINT "service_request_request_ID_not_null" NOT NULL,
    reference_number bigint NOT NULL,
    requestor_id bigint CONSTRAINT "service_request_requestor_ID_not_null" NOT NULL,
    location character varying(255) NOT NULL,
    area character varying(255) NOT NULL,
    description text NOT NULL,
    status character varying(255) DEFAULT 'open'::character varying NOT NULL,
    assigned_to bigint,
    version bigint DEFAULT 0 NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    resolved_at timestamp without time zone,
    category_id bigint NOT NULL,
    CONSTRAINT resolved_after_updated_sanity_check CHECK (((resolved_at IS NULL) OR (resolved_at >= created_at))),
    CONSTRAINT resolved_has_time CHECK ((((status)::text <> ALL ((ARRAY['resolved'::character varying, 'closed'::character varying])::text[])) OR (resolved_at IS NOT NULL))),
    CONSTRAINT status_check CHECK (((status)::text = ANY ((ARRAY['open'::character varying, 'assigned'::character varying, 'in_progress'::character varying, 'resolved'::character varying, 'closed'::character varying])::text[]))),
    CONSTRAINT updated_after_created_sanity_check CHECK ((updated_at >= created_at)),
    CONSTRAINT version_not_negative CHECK ((version >= 0))
);

ALTER TABLE public.service_request ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public."service_request_request_ID_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.users (
    id bigint CONSTRAINT "Users_id_not_null" NOT NULL,
    name character varying(255) CONSTRAINT "Users_name_not_null" NOT NULL,
    email character varying(255) CONSTRAINT "Users_email_not_null" NOT NULL,
    password character varying(255) CONSTRAINT "Users_password_not_null" NOT NULL,
    role character varying(255) DEFAULT 'requestor'::character varying CONSTRAINT "Users_role_not_null" NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP CONSTRAINT "Users_created_at_not_null" NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP CONSTRAINT "Users_updated_at_not_null" NOT NULL,
    CONSTRAINT role_options CHECK (((role)::text = ANY ((ARRAY['requestor'::character varying, 'staff'::character varying, 'management'::character varying])::text[]))),
    CONSTRAINT update_after_created_sanity_check CHECK ((updated_at >= created_at))
);

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT "Users_pkey" PRIMARY KEY (id);

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT categories_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.request_assignments
    ADD CONSTRAINT request_assignments_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.request_comments
    ADD CONSTRAINT request_comments_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.request_status_history
    ADD CONSTRAINT request_status_history_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.request_status_transition
    ADD CONSTRAINT request_status_transition_pkey PRIMARY KEY (old_status, new_status);

ALTER TABLE ONLY public.service_request
    ADD CONSTRAINT service_request_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.categories
    ADD CONSTRAINT unique_code UNIQUE (code);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT unique_email UNIQUE (email);

ALTER TABLE ONLY public.service_request
    ADD CONSTRAINT unique_reference UNIQUE (reference_number);

CREATE INDEX fki_assigned_to_link ON public.request_assignments USING btree (assigned_to);

CREATE INDEX fki_author_link ON public.request_comments USING btree (author_id);

CREATE INDEX fki_category_id_link ON public.service_request USING btree (category_id);

CREATE INDEX fki_changed_by_link ON public.request_status_history USING btree (changed_by);

CREATE INDEX fki_offered_by_link ON public.request_assignments USING btree (offered_by);

CREATE INDEX fki_request_id_link ON public.request_assignments USING btree (request_id);

CREATE INDEX fki_requestor_id_link ON public.service_request USING btree (requestor_id);

CREATE INDEX fki_status_links ON public.request_status_history USING btree (old_status, new_status);

CREATE INDEX idx_comments_request_id ON public.request_comments USING btree (request_id);

CREATE INDEX idx_history_request_id ON public.request_status_history USING btree (request_id);

CREATE INDEX idx_requests_assigned_to ON public.service_request USING btree (assigned_to);

ALTER TABLE ONLY public.request_assignments
    ADD CONSTRAINT assigned_to_link FOREIGN KEY (assigned_to) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE ONLY public.service_request
    ADD CONSTRAINT assigned_to_link FOREIGN KEY (assigned_to) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE ONLY public.request_comments
    ADD CONSTRAINT author_link FOREIGN KEY (author_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE ONLY public.service_request
    ADD CONSTRAINT category_id_link FOREIGN KEY (category_id) REFERENCES public.categories(id) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE ONLY public.request_status_history
    ADD CONSTRAINT changed_by_link FOREIGN KEY (changed_by) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE ONLY public.request_assignments
    ADD CONSTRAINT offered_by_link FOREIGN KEY (offered_by) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE ONLY public.request_assignments
    ADD CONSTRAINT request_id_link FOREIGN KEY (request_id) REFERENCES public.service_request(id) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE ONLY public.request_comments
    ADD CONSTRAINT request_id_link FOREIGN KEY (request_id) REFERENCES public.service_request(id) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE ONLY public.request_status_history
    ADD CONSTRAINT request_id_link FOREIGN KEY (request_id) REFERENCES public.service_request(id) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE ONLY public.service_request
    ADD CONSTRAINT requestor_id_link FOREIGN KEY (requestor_id) REFERENCES public.users(id) ON UPDATE CASCADE ON DELETE RESTRICT;

ALTER TABLE ONLY public.request_status_history
    ADD CONSTRAINT status_links FOREIGN KEY (old_status, new_status) REFERENCES public.request_status_transition(old_status, new_status) ON UPDATE RESTRICT ON DELETE RESTRICT;


-- Reference data: the controlled status workflow (from the original database dump)
INSERT INTO public.request_status_transition (old_status, new_status) VALUES
    ('open', 'assigned'),
    ('assigned', 'in_progress'),
    ('in_progress', 'resolved'),
    ('resolved', 'closed'),
    ('resolved', 'in_progress');
